### ISSUE TITLE
Debugging 

### ISSUE THREAD

**Issue by dbtri68** [awslabs/aws-serverless-metrics-publisher#15]
Apologies I'm not sure how to request assistance but I think this is/could be a very useful app but it doesn't appear to be producing any CW metrics for me.   I see the Logger and Publisher functions being invoked, the cursor is being updated the CheckPointTable but no errors and no mertics.   Is there an Environment variable I can set on the Logger and or Publisher lambda functions to get more detail into their CloudWatch logs?

**Comment by jlhood** [comment]
@dbtri68 This app is no longer necessary for publishing custom metrics to CloudWatch from Lambda functions. You can now write log events to CloudWatch Logs in [Embedded Metric Format](https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-cloudwatch-launches-embedded-metric-format/) and CloudWatch will automatically convert them to CloudWatch Metrics.

**Comment by dbtri68** [comment]
Hi @jlhood , thanks so much for the response I really appreciate it.     Along with a real product name and a link, that's wonderful!
Thanks
DB
